# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=128, unique=True)),
                ('GroupMembers', models.TextField()),
            ],
        ),
    ]
