# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_saltgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255, unique=True)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
