# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_action_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
