# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_delete_customscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=50)),
                ('editor', models.CharField(max_length=50)),
                ('script_code', models.TextField()),
                ('script_type', models.CharField(max_length=15)),
                ('is_parameters', models.CharField(max_length=2)),
                ('comment', models.TextField()),
            ],
        ),
    ]
