# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_customscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customscript',
            name='is_parameters',
        ),
        migrations.AlterField(
            model_name='customscript',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
