# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20170929_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customscript',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
