# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_auto_20170929_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customscript',
            name='script_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
