FROM php:5.6.34-fpm
MAINTAINER zhihuic@quarkfinance.com
RUN apt-get update \
    && apt-get install libldb-dev libldap2-dev zlib1g-dev  -y \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
    && pecl install redis-3.1.0 ldap mysql mysqli pcntl  hash zip gettext sockets bcmath -y \
    && docker-php-ext-enable redis ldap mysql mysqli pcntl  hash zip gettext sockets bcmath 
